require 'codeclimate-test-reporter'
CodeClimate::TestReporter.start

require 'pry'
require 'sass'
require 'yaml'
require 'monet/config'
require 'monet/errors'
require 'monet/engine'
require 'monet/scheme/colour_map'
require 'monet/scheme/section'
require 'monet/scheme/reference'
require 'monet/scheme/colour'
require 'monet/colour_scheme'
require 'monet/helpers'
